// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matrixa_matrixa,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.877000,HLS_SYN_LAT=12,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=31,HLS_SYN_LUT=178,HLS_VERSION=2022_2}" *)

module matrixa (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_0_address0,
        a_0_ce0,
        a_0_q0,
        a_1_address0,
        a_1_ce0,
        a_1_q0,
        b_0_address0,
        b_0_ce0,
        b_0_q0,
        b_1_address0,
        b_1_ce0,
        b_1_q0,
        result_address0,
        result_ce0,
        result_we0,
        result_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] a_0_address0;
output   a_0_ce0;
input  [7:0] a_0_q0;
output  [2:0] a_1_address0;
output   a_1_ce0;
input  [7:0] a_1_q0;
output  [2:0] b_0_address0;
output   b_0_ce0;
input  [7:0] b_0_q0;
output  [2:0] b_1_address0;
output   b_1_ce0;
input  [7:0] b_1_q0;
output  [3:0] result_address0;
output   result_ce0;
output   result_we0;
output  [31:0] result_d0;

reg ap_idle;
reg a_0_ce0;
reg a_1_ce0;
reg b_0_ce0;
reg b_1_ce0;
reg result_ce0;
reg result_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln5_fu_159_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] select_ln5_fu_189_p3;
reg   [1:0] select_ln5_reg_345;
reg   [1:0] select_ln5_reg_345_pp0_iter1_reg;
wire   [1:0] select_ln5_1_fu_197_p3;
reg   [1:0] select_ln5_1_reg_350;
reg   [1:0] select_ln5_1_reg_350_pp0_iter1_reg;
reg   [0:0] tmp_4_reg_376;
wire   [8:0] add_ln10_fu_280_p2;
reg   [8:0] add_ln10_reg_382;
wire   [63:0] zext_ln10_1_fu_217_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln10_3_fu_311_p1;
reg   [1:0] j_fu_64;
wire   [1:0] add_ln7_fu_233_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_j_load;
reg   [1:0] i_fu_68;
reg   [1:0] ap_sig_allocacmp_i_load;
reg   [3:0] indvar_flatten_fu_72;
wire   [3:0] add_ln5_1_fu_165_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln7_fu_183_p2;
wire   [1:0] add_ln5_fu_177_p2;
wire   [0:0] empty_6_fu_205_p1;
wire   [2:0] tmp_3_fu_209_p3;
wire   [7:0] tmp_fu_254_p4;
wire   [7:0] tmp_1_fu_267_p4;
wire  signed [8:0] sext_ln10_1_fu_276_p1;
wire  signed [8:0] sext_ln10_fu_263_p1;
wire   [3:0] tmp_2_fu_289_p3;
wire   [3:0] zext_ln10_fu_286_p1;
wire   [3:0] sub_ln10_fu_296_p2;
wire   [3:0] zext_ln10_2_fu_302_p1;
wire   [3:0] add_ln10_1_fu_305_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

matrixa_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U1(
    .din0(a_0_q0),
    .din1(a_1_q0),
    .din2(tmp_4_reg_376),
    .dout(tmp_fu_254_p4)
);

matrixa_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U2(
    .din0(b_0_q0),
    .din1(b_1_q0),
    .din2(tmp_4_reg_376),
    .dout(tmp_1_fu_267_p4)
);

matrixa_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_127)) begin
        if ((icmp_ln5_fu_159_p2 == 1'd0)) begin
            i_fu_68 <= select_ln5_1_fu_197_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_127)) begin
        if ((icmp_ln5_fu_159_p2 == 1'd0)) begin
            indvar_flatten_fu_72 <= add_ln5_1_fu_165_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_72 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_127)) begin
        if ((icmp_ln5_fu_159_p2 == 1'd0)) begin
            j_fu_64 <= add_ln7_fu_233_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_64 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln10_reg_382 <= add_ln10_fu_280_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        select_ln5_1_reg_350_pp0_iter1_reg <= select_ln5_1_reg_350;
        select_ln5_reg_345_pp0_iter1_reg <= select_ln5_reg_345;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln5_fu_159_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln5_1_reg_350 <= select_ln5_1_fu_197_p3;
        select_ln5_reg_345 <= select_ln5_fu_189_p3;
        tmp_4_reg_376 <= select_ln5_fu_189_p3[32'd1];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_0_ce0 = 1'b1;
    end else begin
        a_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        a_1_ce0 = 1'b1;
    end else begin
        a_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln5_fu_159_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 2'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_load = 2'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_0_ce0 = 1'b1;
    end else begin
        b_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        b_1_ce0 = 1'b1;
    end else begin
        b_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result_ce0 = 1'b1;
    end else begin
        result_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        result_we0 = 1'b1;
    end else begin
        result_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_0_address0 = zext_ln10_1_fu_217_p1;

assign a_1_address0 = zext_ln10_1_fu_217_p1;

assign add_ln10_1_fu_305_p2 = (sub_ln10_fu_296_p2 + zext_ln10_2_fu_302_p1);

assign add_ln10_fu_280_p2 = ($signed(sext_ln10_1_fu_276_p1) + $signed(sext_ln10_fu_263_p1));

assign add_ln5_1_fu_165_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln5_fu_177_p2 = (ap_sig_allocacmp_i_load + 2'd1);

assign add_ln7_fu_233_p2 = (select_ln5_fu_189_p3 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_127 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign b_0_address0 = zext_ln10_1_fu_217_p1;

assign b_1_address0 = zext_ln10_1_fu_217_p1;

assign empty_6_fu_205_p1 = select_ln5_fu_189_p3[0:0];

assign icmp_ln5_fu_159_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_183_p2 = ((ap_sig_allocacmp_j_load == 2'd3) ? 1'b1 : 1'b0);

assign result_address0 = zext_ln10_3_fu_311_p1;

assign result_d0 = $signed(add_ln10_reg_382);

assign select_ln5_1_fu_197_p3 = ((icmp_ln7_fu_183_p2[0:0] == 1'b1) ? add_ln5_fu_177_p2 : ap_sig_allocacmp_i_load);

assign select_ln5_fu_189_p3 = ((icmp_ln7_fu_183_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_j_load);

assign sext_ln10_1_fu_276_p1 = $signed(tmp_1_fu_267_p4);

assign sext_ln10_fu_263_p1 = $signed(tmp_fu_254_p4);

assign sub_ln10_fu_296_p2 = (tmp_2_fu_289_p3 - zext_ln10_fu_286_p1);

assign tmp_2_fu_289_p3 = {{select_ln5_1_reg_350_pp0_iter1_reg}, {2'd0}};

assign tmp_3_fu_209_p3 = {{select_ln5_1_fu_197_p3}, {empty_6_fu_205_p1}};

assign zext_ln10_1_fu_217_p1 = tmp_3_fu_209_p3;

assign zext_ln10_2_fu_302_p1 = select_ln5_reg_345_pp0_iter1_reg;

assign zext_ln10_3_fu_311_p1 = add_ln10_1_fu_305_p2;

assign zext_ln10_fu_286_p1 = select_ln5_1_reg_350_pp0_iter1_reg;

endmodule //matrixa
